# Generated by Django 3.2.16 on 2025-12-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20251227_2341'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_post_id_5fee65_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_author__9faedb_idx',
        ),
    ]
